In [2]:
import os

os.listdir()

['analysis.ipynb',
 'Data Analyst Assignment.pdf',
 'Orders',
 'People.csv',
 'Returns.csv',
 'Target.csv']

In [3]:
import pandas as pd

people=pd.read_csv("People.csv")
returns=pd.read_csv("Returns.csv")
target=pd.read_csv("Target.csv")

In [4]:
target.describe

<bound method NDFrame.describe of            Category  Year Sales Target
0   Office Supplies  2015         170K
1        Technology  2015         180K
2         Furniture  2015         190K
3   Office Supplies  2016         190K
4        Technology  2016         180K
5         Furniture  2016         200K
6   Office Supplies  2017         200K
7        Technology  2017         210K
8         Furniture  2017         260K
9   Office Supplies  2018         190K
10       Technology  2018         180K
11        Furniture  2018         200K
12  Office Supplies  2019         160K
13       Technology  2019         180K
14        Furniture  2019         200K>

In [5]:
people.describe

<bound method NDFrame.describe of     Region            People
0    North  Ross DeVincentis
1    South   Damala Kotsonis
2  Central       Emily Burns>

In [6]:
returns.describe

<bound method NDFrame.describe of             Order ID Returned
0    ES-2015-1137137      Yes
1    ES-2015-1141056      Yes
2    ES-2015-1228490      Yes
3    ES-2015-1228490      Yes
4    ES-2015-1228490      Yes
..               ...      ...
632  IT-2018-5470294      Yes
633  IT-2018-5470294      Yes
634  IT-2018-5470294      Yes
635  IT-2018-5470294      Yes
636  IT-2018-5517515      Yes

[637 rows x 2 columns]>

In [7]:
target.columns

Index(['Category', 'Year', 'Sales Target'], dtype='object')

In [8]:
people.columns

Index(['Region', 'People'], dtype='object')

In [9]:
returns.columns

Index(['Order ID', 'Returned'], dtype='object')

In [10]:
order1=pd.read_csv("Orders/order_2015.csv")

In [11]:
order1.describe

<bound method NDFrame.describe of              Order ID  Order Date  Ship Date       Ship Mode Customer ID  \
0     ES-2015-2801336       42157      42161  Standard Class    DB-13270
1     ES-2015-3186072       42275      42279  Standard Class    CA-12265
2     ES-2015-3186072       42275      42279  Standard Class    CA-12265
3     ES-2015-3186072       42275      42279  Standard Class    CA-12265
4     ES-2015-5235241       42243      42244        Same Day    TB-21175
...               ...         ...        ...             ...         ...
1648  ES-2015-5483343       42242      42246  Standard Class    TS-21205
1649  ES-2015-3081212       42244      42251  Standard Class    VW-21775
1650  ES-2015-3081212       42244      42251  Standard Class    VW-21775
1651  ES-2015-3081212       42244      42251  Standard Class    VW-21775
1652  ES-2015-3780358       42324      42327     First Class    CC-12100

           Customer Name      Segment           City          State  \
0      Deborah Brumfield  Home Office      Barcelona      Catalonia
1     Christina Anderson     Consumer  Littlehampton        England
2     Christina Anderson     Consumer  Littlehampton        England
3     Christina Anderson     Consumer  Littlehampton        England
4          Thomas Boland    Corporate        Taverny  Ile-de-France
...                  ...          ...            ...            ...
1648         Thomas Seio    Corporate        Paisley       Scotland
1649     Victoria Wilson    Corporate       Helsinki        Uusimaa
1650     Victoria Wilson    Corporate       Helsinki        Uusimaa
1651     Victoria Wilson    Corporate       Helsinki        Uusimaa
1652     Chad Cunningham  Home Office         Rovigo         Veneto

             Country   Region       Product ID         Category Sub-Category  \
0              Spain    South  OFF-BI-10002225  Office Supplies      Binders
1     United Kingdom    North  TEC-CO-10000620       Technology      Copiers
2     United Kingdom    North  TEC-AC-10004203       Technology  Accessories
3     United Kingdom    North  TEC-CO-10001596       Technology      Copiers
4             France  Central  OFF-SU-10004818  Office Supplies     Supplies
...              ...      ...              ...              ...          ...
1648  United Kingdom    North  OFF-AR-10003651  Office Supplies          Art
1649         Finland    North  FUR-CH-10001831        Furniture       Chairs
1650         Finland    North  OFF-LA-10003290  Office Supplies       Labels
1651         Finland    North  OFF-AP-10002238  Office Supplies   Appliances
1652           Italy    South  OFF-BI-10000346  Office Supplies      Binders

                           Product Name    Sales  Quantity  Discount  Profit
0     Cardinal Binding Machine, Durable   102.54         2       0.0   35.88
1         Brother Wireless Fax, Digital  1892.25         5       0.0  170.25
2       Logitech Flash Drive, Bluetooth   122.04         4       0.0   52.44
3           Brother Wireless Fax, Color  1140.75         3       0.0  239.49
4               Stiletto Trimmer, Steel    84.30         2       0.0   28.62
...                                 ...      ...       ...       ...     ...
1648           Sanford Pens, Easy-Erase    34.11         3       0.0    7.83
1649  Novimex Rocking Chair, Set of Two   267.36         2       0.0   29.40
1650       Hon Round Labels, Adjustable     9.12         2       0.0    3.24
1651         Hoover Coffee Grinder, Red   275.16         4       0.0    8.16
1652          Ibico 3-Hole Punch, Clear    59.82         2       0.0   23.88

[1653 rows x 19 columns]>

In [12]:
order2=pd.read_csv("Orders/order_2016.csv")

In [13]:
order3=pd.read_csv("Orders/order_2017.csv")

In [14]:
order4=pd.read_csv("Orders/order_2018.csv")

In [15]:
order=pd.concat(
    [order1, order2, order3, order4],
    ignore_index=True
)

In [16]:
order.shape

(10000, 19)

In [17]:
order.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'City', 'State', 'Country', 'Region',
       'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales',
       'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [18]:
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       10000 non-null  object
 1   Order Date     10000 non-null  int64
 2   Ship Date      10000 non-null  int64
 3   Ship Mode      10000 non-null  object
 4   Customer ID    10000 non-null  object
 5   Customer Name  10000 non-null  object
 6   Segment        10000 non-null  object
 7   City           10000 non-null  object
 8   State          10000 non-null  object
 9   Country        10000 non-null  object
 10  Region         10000 non-null  object
 11  Product ID     10000 non-null  object
 12  Category       10000 non-null  object
 13  Sub-Category   10000 non-null  object
 14  Product Name   10000 non-null  object
 15  Sales          10000 non-null  float64
 16  Quantity       10000 non-null  object
 17  Discount       10000 non-null  float64
 18  Profit         10000 non-null  float64
dtypes: float64(3), int64(2), object(14)
memory usage: 1.4+ MB

In [19]:
order.isnull().sum()

Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
City             0
State            0
Country          0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [20]:
order.describe()

         Order Date     Ship Date         Sales      Discount        Profit
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000
mean   42869.629000  42873.635000    293.808906      0.103105     37.282974
std      411.746281    411.766159    486.055635      0.174782    178.100384
min    42005.000000  42009.000000      2.955000      0.000000  -3059.820000
25%    42551.000000  42556.000000     49.462500      0.000000      1.320000
50%    42925.000000  42927.000000    119.355000      0.000000     14.220000
75%    43254.000000  43257.000000    320.708625      0.100000     48.510000
max    43465.000000  43470.000000   7958.580000      0.850000   3979.080000

In [21]:
import pandas as pd

order["Order Date"] = pd.to_datetime(
    order["Order Date"],
    unit="D",
    origin="1899-12-30"
)

order["Ship Date"] = pd.to_datetime(
    order["Ship Date"],
    unit="D",
    origin="1899-12-30"
)

In [22]:
order[["Order Date", "Ship Date"]].head()

  Order Date  Ship Date
0 2015-06-02 2015-06-06
1 2015-09-28 2015-10-02
2 2015-09-28 2015-10-02
3 2015-09-28 2015-10-02
4 2015-08-27 2015-08-28

In [23]:
order["Quantity"].unique()

array([2, 5, 4, 3, 6, 7, 8, 1, 9, 12, 10, 11, 14, 13, '3', '7', '2', '5',
       '1', '4', '6', '9', '14', '8', '10', '11', '12', '13', 'one',
       'six', 'ten', 'nine'], dtype=object)

In [24]:
quantity_map = {
    "one":1,
    "two":2,
    "three":3,
    "four":4,
    "five":5,
    "six":6,
    "seven":7,
    "eight":8,
    "nine":9,
    "ten":10
}

order["Quantity"]=(
    order["Quantity"].replace(quantity_map).astype(int)
)

In [25]:
sorted(order["Quantity"].unique())

[np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14)]

In [26]:
order["Order Year"] = order["Order Date"].dt.year

order.groupby("Order Year").agg({
    "Sales": "sum",
    "Profit": "sum",
    "Order ID": "nunique"
})

                   Sales       Profit  Order ID
Order Year
2015        4.777967e+05   61376.1750       806
2016        6.526474e+05   84024.8160      1038
2017        7.654412e+05   98484.3930      1214
2018        1.042204e+06  128944.3575      1538

In [27]:
yearly = order.groupby("Order Year").agg({
    "Sales":"sum",
    "Profit":"sum",
    "Order ID":"nunique"
})

yearly["Sales YoY %"] = yearly["Sales"].pct_change()*100
yearly["Sales YoY %"] = yearly["Profit"].pct_change()*100
yearly["Sales YoY %"] = yearly["Order ID"].pct_change()*100

yearly.round(2)

                 Sales     Profit  Order ID  Sales YoY %
Order Year
2015         477796.72   61376.18       806          NaN
2016         652647.37   84024.82      1038        28.78
2017         765441.24   98484.39      1214        16.96
2018        1042203.73  128944.36      1538        26.69

In [28]:
order.groupby("Category").agg({
    "Sales":"sum",
    "Profit":"sum",
    "Order ID":"nunique"
}).sort_values("Sales", ascending=False)

                        Sales       Profit  Order ID
Category
Technology       1.112679e+06  144272.6580      1577
Office Supplies  1.046307e+06  159706.9440      3717
Furniture        7.791030e+05   68850.1395      1292

In [29]:
order.groupby("Category").agg({
    "Sales":"sum",
    "Profit":"sum"
}).assign(
    Profit_Margin=lambda x: x["Profit"] / x["Sales"] * 100
).round(2)

                      Sales     Profit  Profit_Margin
Category
Furniture         779103.05   68850.14           8.84
Office Supplies  1046307.02  159706.94          15.26
Technology       1112678.99  144272.66          12.97

In [30]:
order.groupby("Region").agg({
    "Sales":"sum",
    "Profit":"sum",
    "Order ID":"nunique"
}).sort_values("Sales", ascending=False)

                Sales       Profit  Order ID
Region
Central  1.720553e+06  215534.0685      2579
North    6.255750e+05   91779.8550      1027
South    5.919615e+05   65515.8180       995

In [31]:
region = order.groupby("Region").agg({
    "Sales":"sum",
    "Profit":"sum",
    "Order ID":"nunique"
})

region["Sales Share %"] = (
    region["Sales"] /
    region["Sales"].sum() * 100
)

region.round(2)

              Sales     Profit  Order ID  Sales Share %
Region
Central  1720552.62  215534.07      2579          58.56
North     625574.98   91779.86      1027          21.29
South     591961.46   65515.82       995          20.15

In [32]:
people

    Region            People
0    North  Ross DeVincentis
1    South   Damala Kotsonis
2  Central       Emily Burns

In [33]:
target

           Category  Year Sales Target
0   Office Supplies  2015         170K
1        Technology  2015         180K
2         Furniture  2015         190K
3   Office Supplies  2016         190K
4        Technology  2016         180K
5         Furniture  2016         200K
6   Office Supplies  2017         200K
7        Technology  2017         210K
8         Furniture  2017         260K
9   Office Supplies  2018         190K
10       Technology  2018         180K
11        Furniture  2018         200K
12  Office Supplies  2019         160K
13       Technology  2019         180K
14        Furniture  2019         200K

In [34]:
order = order.merge(
    people,
    on="Region",
    how="left"
)

order.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order Year,People
0,ES-2015-2801336,2015-06-02,2015-06-06,Standard Class,DB-13270,Deborah Brumfield,Home Office,Barcelona,Catalonia,Spain,...,OFF-BI-10002225,Office Supplies,Binders,"Cardinal Binding Machine, Durable",102.54,2,0.0,35.88,2015,Damala Kotsonis
1,ES-2015-3186072,2015-09-28,2015-10-02,Standard Class,CA-12265,Christina Anderson,Consumer,Littlehampton,England,United Kingdom,...,TEC-CO-10000620,Technology,Copiers,"Brother Wireless Fax, Digital",1892.25,5,0.0,170.25,2015,Ross DeVincentis
2,ES-2015-3186072,2015-09-28,2015-10-02,Standard Class,CA-12265,Christina Anderson,Consumer,Littlehampton,England,United Kingdom,...,TEC-AC-10004203,Technology,Accessories,"Logitech Flash Drive, Bluetooth",122.04,4,0.0,52.44,2015,Ross DeVincentis
3,ES-2015-3186072,2015-09-28,2015-10-02,Standard Class,CA-12265,Christina Anderson,Consumer,Littlehampton,England,United Kingdom,...,TEC-CO-10001596,Technology,Copiers,"Brother Wireless Fax, Color",1140.75,3,0.0,239.49,2015,Ross DeVincentis
4,ES-2015-5235241,2015-08-27,2015-08-28,Same Day,TB-21175,Thomas Boland,Corporate,Taverny,Ile-de-France,France,...,OFF-SU-10004818,Office Supplies,Supplies,"Stiletto Trimmer, Steel",84.30,2,0.0,28.62,2015,Emily Burns

In [35]:
order.groupby("People").agg({
    "Sales":"sum",
    "Profit":"sum",
    "Order ID":"nunique"
}).round(2)

                       Sales     Profit  Order ID
People
Damala Kotsonis    591961.46   65515.82       995
Emily Burns       1720552.62  215534.07      2579
Ross DeVincentis   625574.98   91779.86      1027

In [36]:
target

           Category  Year Sales Target
0   Office Supplies  2015         170K
1        Technology  2015         180K
2         Furniture  2015         190K
3   Office Supplies  2016         190K
4        Technology  2016         180K
5         Furniture  2016         200K
6   Office Supplies  2017         200K
7        Technology  2017         210K
8         Furniture  2017         260K
9   Office Supplies  2018         190K
10       Technology  2018         180K
11        Furniture  2018         200K
12  Office Supplies  2019         160K
13       Technology  2019         180K
14        Furniture  2019         200K

In [37]:
target["Sales Target"] = (
    target["Sales Target"]
    .str.replace("K", "", regex=False)
    .astype(int) * 1000
)

In [38]:
target.head()

          Category  Year  Sales Target
0  Office Supplies  2015        170000
1       Technology  2015        180000
2        Furniture  2015        190000
3  Office Supplies  2016        190000
4       Technology  2016        180000

In [39]:
order["Order Year"] = order["Order Date"].dt.year

In [40]:
order[["Order Date","Order Year"]].head()

  Order Date  Order Year
0 2015-06-02        2015
1 2015-09-28        2015
2 2015-09-28        2015
3 2015-09-28        2015
4 2015-08-27        2015

In [41]:
actual_sales = (
    order.groupby(["Order Year", "Category"])["Sales"]
    .sum()
    .reset_index()
)

actual_sales.head()

   Order Year         Category        Sales
0        2015        Furniture  138946.3395
1        2015  Office Supplies  178844.5440
2        2015       Technology  160005.8415
3        2016        Furniture  172180.5375
4        2016  Office Supplies  225317.2440

In [42]:
target.columns

Index(['Category', 'Year', 'Sales Target'], dtype='object')

In [43]:
target["Sales Target"] = (
    target["Sales Target"]
    #.str.replace("K", "", regex=False)
    .astype(int) * 1000
)

order["Order Year"] = order["Order Date"].dt.year

actual_sales = (
    order.groupby(["Order Year", "Category"])["Sales"]
    .sum()
    .reset_index()
)

actual_sales.head()
target.dtypes

Category        object
Year             int64
Sales Target     int64
dtype: object

In [44]:
achievement = (
    order.groupby(["Order Year", "Category"])["Sales"]
    .sum()
    .reset_index()
)

achievement = achievement.merge(
    target,
    left_on=["Order Year", "Category"],
    right_on=["Year", "Category"],
    how="left"
)

achievement["Achievement %"] = (
    achievement["Sales"] /
    achievement["Sales Target"]
) * 100

achievement.round(2)

    Order Year         Category      Sales  Year  Sales Target  Achievement %
0         2015        Furniture  138946.34  2015     190000000           0.07
1         2015  Office Supplies  178844.54  2015     170000000           0.11
2         2015       Technology  160005.84  2015     180000000           0.09
3         2016        Furniture  172180.54  2016     200000000           0.09
4         2016  Office Supplies  225317.24  2016     190000000           0.12
5         2016       Technology  255149.58  2016     180000000           0.14
6         2017        Furniture  201712.62  2017     260000000           0.08
7         2017  Office Supplies  279343.98  2017     200000000           0.14
8         2017       Technology  284384.65  2017     210000000           0.14
9         2018        Furniture  266263.56  2018     200000000           0.13
10        2018  Office Supplies  362801.26  2018     190000000           0.19
11        2018       Technology  413138.91  2018     180000000           0.23

In [45]:
achievement.sort_values(
    "Achievement %",
    ascending=False
).round(2)

    Order Year         Category      Sales  Year  Sales Target  Achievement %
11        2018       Technology  413138.91  2018     180000000           0.23
10        2018  Office Supplies  362801.26  2018     190000000           0.19
5         2016       Technology  255149.58  2016     180000000           0.14
7         2017  Office Supplies  279343.98  2017     200000000           0.14
8         2017       Technology  284384.65  2017     210000000           0.14
9         2018        Furniture  266263.56  2018     200000000           0.13
4         2016  Office Supplies  225317.24  2016     190000000           0.12
1         2015  Office Supplies  178844.54  2015     170000000           0.11
2         2015       Technology  160005.84  2015     180000000           0.09
3         2016        Furniture  172180.54  2016     200000000           0.09
6         2017        Furniture  201712.62  2017     260000000           0.08
0         2015        Furniture  138946.34  2015     190000000           0.07

In [46]:
target.head()

          Category  Year  Sales Target
0  Office Supplies  2015     170000000
1       Technology  2015     180000000
2        Furniture  2015     190000000
3  Office Supplies  2016     190000000
4       Technology  2016     180000000

In [47]:
target["Sales Target"] = target["Sales Target"] / 1000

In [48]:
target.head()

          Category  Year  Sales Target
0  Office Supplies  2015      170000.0
1       Technology  2015      180000.0
2        Furniture  2015      190000.0
3  Office Supplies  2016      190000.0
4       Technology  2016      180000.0

In [49]:
achievement.sort_values(
    ["Order Year", "Achievement %"],
    ascending=[True, False]
).round(2)

    Order Year         Category      Sales  Year  Sales Target  Achievement %
1         2015  Office Supplies  178844.54  2015     170000000           0.11
2         2015       Technology  160005.84  2015     180000000           0.09
0         2015        Furniture  138946.34  2015     190000000           0.07
5         2016       Technology  255149.58  2016     180000000           0.14
4         2016  Office Supplies  225317.24  2016     190000000           0.12
3         2016        Furniture  172180.54  2016     200000000           0.09
7         2017  Office Supplies  279343.98  2017     200000000           0.14
8         2017       Technology  284384.65  2017     210000000           0.14
6         2017        Furniture  201712.62  2017     260000000           0.08
11        2018       Technology  413138.91  2018     180000000           0.23
10        2018  Office Supplies  362801.26  2018     190000000           0.19
9         2018        Furniture  266263.56  2018     200000000           0.13

In [50]:
achievement = (
    order.groupby(["Order Year", "Category"])["Sales"]
    .sum()
    .reset_index()
)

achievement = achievement.merge(
    target,
    left_on=["Order Year", "Category"],
    right_on=["Year", "Category"],
    how="left"
)

achievement["Achievement %"] = (
    achievement["Sales"] /
    achievement["Sales Target"]
) * 100

achievement.round(2)

    Order Year         Category      Sales  Year  Sales Target  Achievement %
0         2015        Furniture  138946.34  2015      190000.0          73.13
1         2015  Office Supplies  178844.54  2015      170000.0         105.20
2         2015       Technology  160005.84  2015      180000.0          88.89
3         2016        Furniture  172180.54  2016      200000.0          86.09
4         2016  Office Supplies  225317.24  2016      190000.0         118.59
5         2016       Technology  255149.58  2016      180000.0         141.75
6         2017        Furniture  201712.62  2017      260000.0          77.58
7         2017  Office Supplies  279343.98  2017      200000.0         139.67
8         2017       Technology  284384.65  2017      210000.0         135.42
9         2018        Furniture  266263.56  2018      200000.0         133.13
10        2018  Office Supplies  362801.26  2018      190000.0         190.95
11        2018       Technology  413138.91  2018      180000.0         229.52

In [51]:
achievement.sort_values(
    "Achievement %",
    ascending=False
).round(2)

    Order Year         Category      Sales  Year  Sales Target  Achievement %
11        2018       Technology  413138.91  2018      180000.0         229.52
10        2018  Office Supplies  362801.26  2018      190000.0         190.95
5         2016       Technology  255149.58  2016      180000.0         141.75
7         2017  Office Supplies  279343.98  2017      200000.0         139.67
8         2017       Technology  284384.65  2017      210000.0         135.42
9         2018        Furniture  266263.56  2018      200000.0         133.13
4         2016  Office Supplies  225317.24  2016      190000.0         118.59
1         2015  Office Supplies  178844.54  2015      170000.0         105.20
2         2015       Technology  160005.84  2015      180000.0          88.89
3         2016        Furniture  172180.54  2016      200000.0          86.09
6         2017        Furniture  201712.62  2017      260000.0          77.58
0         2015        Furniture  138946.34  2015      190000.0          73.13

In [52]:
achievement.sort_values(
    ["Order Year", "Achievement %"],
    ascending=[True, False]
).round(2)

    Order Year         Category      Sales  Year  Sales Target  Achievement %
1         2015  Office Supplies  178844.54  2015      170000.0         105.20
2         2015       Technology  160005.84  2015      180000.0          88.89
0         2015        Furniture  138946.34  2015      190000.0          73.13
5         2016       Technology  255149.58  2016      180000.0         141.75
4         2016  Office Supplies  225317.24  2016      190000.0         118.59
3         2016        Furniture  172180.54  2016      200000.0          86.09
7         2017  Office Supplies  279343.98  2017      200000.0         139.67
8         2017       Technology  284384.65  2017      210000.0         135.42
6         2017        Furniture  201712.62  2017      260000.0          77.58
11        2018       Technology  413138.91  2018      180000.0         229.52
10        2018  Office Supplies  362801.26  2018      190000.0         190.95
9         2018        Furniture  266263.56  2018      200000.0         133.13

In [53]:
returns.shape

(637, 2)

In [54]:
returns.head()

          Order ID Returned
0  ES-2015-1137137      Yes
1  ES-2015-1141056      Yes
2  ES-2015-1228490      Yes
3  ES-2015-1228490      Yes
4  ES-2015-1228490      Yes

In [55]:
returns["Returned"].value_counts()

Returned
Yes    637
Name: count, dtype: int64

In [56]:
returns["Order ID"].nunique()

284

In [57]:
order["Order ID"].nunique()

4596

In [58]:
return_rate = (
    returns["Order ID"].nunique()
    /
    order["Order ID"].nunique()
) * 100

return_rate

6.179286335944299

In [59]:
returned_orders = set(returns["Order ID"])

order["Returned"] = order["Order ID"].isin(returned_orders)

In [60]:
order["Returned"].value_counts()

Returned
False    9363
True      637
Name: count, dtype: int64

In [61]:
order.groupby("Category")["Returned"].mean() * 100

Category
Furniture          6.595603
Office Supplies    6.116254
Technology         7.068063
Name: Returned, dtype: float64

In [62]:
returns["Order ID"].nunique()

order["Order ID"].nunique()

order["Returned"] = order["Order ID"].isin(
    set(returns["Order ID"])
)

order["Returned"].value_counts()

order.groupby("Category")["Returned"].mean() * 100

Category
Furniture          6.595603
Office Supplies    6.116254
Technology         7.068063
Name: Returned, dtype: float64

In [63]:
order["Delivery Days"] = (
    order["Ship Date"] - order["Order Date"]
).dt.days

In [64]:
order["Delivery Days"].describe()

count    10000.000000
mean         4.006000
std          1.743866
min          0.000000
25%          3.000000
50%          4.000000
75%          5.000000
max          8.000000
Name: Delivery Days, dtype: float64

In [65]:
order.groupby("Ship Mode")["Delivery Days"].mean()

Ship Mode
First Class       2.199450
Same Day          0.042636
Second Class      3.236842
Standard Class    5.028741
Name: Delivery Days, dtype: float64

In [66]:
order["Delayed"] = order["Delivery Days"] > 5

order["Delayed"].mean() * 100

np.float64(19.34)

In [67]:
order.groupby("Category")["Delayed"].mean() * 100

Category
Furniture          17.854763
Office Supplies    19.395963
Technology         20.314136
Name: Delayed, dtype: float64

In [68]:
order.groupby("Returned")["Delivery Days"].mean()

Returned
False    4.013778
True     3.891680
Name: Delivery Days, dtype: float64

In [69]:
manager_category = (
    order.groupby(["People", "Category"])
    .agg({
        "Sales":"sum",
        "Profit":"sum",
        "Order ID":"nunique"
    })
    .reset_index()
)

manager_category

             People         Category        Sales      Profit  Order ID
0   Damala Kotsonis        Furniture  146840.0820  10101.9120       264
1   Damala Kotsonis  Office Supplies  234607.6860  37575.1860       798
2   Damala Kotsonis       Technology  210513.6900  17838.7200       320
3       Emily Burns        Furniture  470359.3095  38210.1795       759
4       Emily Burns  Office Supplies  597662.9850  96408.4050      2092
5       Emily Burns       Technology  652530.3240  80915.4840       914
6  Ross DeVincentis        Furniture  161903.6580  20538.0480       269
7  Ross DeVincentis  Office Supplies  214036.3530  25723.3530       831
8  Ross DeVincentis       Technology  249634.9740  45518.4540       343

In [70]:
order.to_csv("Orders.csv", index=False)

In [72]:
order.shape

(10000, 24)